### ISSUE TITLE
Raises exception when parameters are used in the expression

### ISSUE THREAD

**Issue by stecydube** [halllo/Result.OrDefault#1]
Given the following code:

string value = "abc";
string result = Result.OrDefault (() => value.ToString (CultureInfo.InvariantCulture));

The following exception is raised: System.Reflection.TargetParameterCountException : Parameter count mismatch.

**Comment by halllo** [comment]
Yes, that definitively should be supported. Could be big if closures are used :(

**Comment by stecydube** [comment]
Great, thank you!

However I found other issues, I've raised a new issue.
