### ISSUE TITLE
Got an ArgumentNullException when accessing a field from a field from an instance

### ISSUE THREAD

**Issue by stecydube** [halllo/Result.OrDefault#5]
Another variation on a similar theme as issue #4 

public class SomeClass
{
public SomeClass () {Field = "field";}
public string Field;
}
...
private static SomeClass _someStaticInstance = new SomeClass ();
...
var result = Result.OrDefault (() => _someStaticInstance.Field);

**Comment by halllo** [comment]
thanks a lot for testing!

**Comment by stecydube** [comment]
Impeccable! Thanks a million for the fixes.
